services:
  - type: web
    name: gym-booker
    env: node
    buildCommand: yarn && yarn playwright install chromium --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATA_DIR
        value: /opt/render/project/data
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
